name: destine-analysis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - cartopy
  - earthkit-geo
  - healpy
  - ipykernel
  - lxml
  - matplotlib
  - netcdf4
  - numcodecs<0.16
  - numpy
  - pandas
  - pydantic
  - xarray
  - zarr>=2.18,<3
  - pip
  - pip:
    - conflator
    - covjsonkit
    - earthkit-data
    - polytope-client
